name: aura_luxury_reservations
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  cloud_firestore: ^6.6.0
  device_preview: ^1.3.1
  firebase_auth: ^6.5.4
  firebase_core: ^4.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  google_fonts: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
