// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVKoRAMut_quDZkmebqdtUMl-m_mzWIU',
    appId: '1:765770993044:web:663689caf3450628e65381',
    messagingSenderId: '765770993044',
    projectId: 'lumiere-c377e',
    authDomain: 'lumiere-c377e.firebaseapp.com',
    storageBucket: 'lumiere-c377e.firebasestorage.app',
    measurementId: 'G-Z8J67V7XR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHwhqbM3z3RZCShq8J1BiRcA2s7liksPU',
    appId: '1:765770993044:android:ab3924392c5f2cd2e65381',
    messagingSenderId: '765770993044',
    projectId: 'lumiere-c377e',
    storageBucket: 'lumiere-c377e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY8vXQdNrrY4BMpF9Lws5mu3HN7BWX9QU',
    appId: '1:765770993044:ios:f4066e24d1656124e65381',
    messagingSenderId: '765770993044',
    projectId: 'lumiere-c377e',
    storageBucket: 'lumiere-c377e.firebasestorage.app',
    iosBundleId: 'com.example.auraLuxuryReservations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY8vXQdNrrY4BMpF9Lws5mu3HN7BWX9QU',
    appId: '1:765770993044:ios:f4066e24d1656124e65381',
    messagingSenderId: '765770993044',
    projectId: 'lumiere-c377e',
    storageBucket: 'lumiere-c377e.firebasestorage.app',
    iosBundleId: 'com.example.auraLuxuryReservations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeVKoRAMut_quDZkmebqdtUMl-m_mzWIU',
    appId: '1:765770993044:web:59c2298b8162d33ae65381',
    messagingSenderId: '765770993044',
    projectId: 'lumiere-c377e',
    authDomain: 'lumiere-c377e.firebaseapp.com',
    storageBucket: 'lumiere-c377e.firebasestorage.app',
    measurementId: 'G-54YHNVWECR',
  );
}
